config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|de/ do

    get '/contact' => 'static#contact'
    get '/about' => 'static#about'

    resources :breeders

    resources :horses do
      member do
        get 'progeny'
      end
    end

    devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end

    devise_scope :user do
      get "signout", :to => "devise/sessions#destroy"
    end

    root :to => 'home#index'
    get '/:locale' => 'home#index'

  end

end

app/models/breeder.rb
class Breeder < ActiveRecord::Base
  default_scope { order('name ASC') }

  has_many :horses, foreign_key: :breeder_id

  validates :name, presence: true
  validates :name, uniqueness: true

  def self.search_name(search_name)
    if search_name
      # ILIKE == case-insensitive LIKE for PostgreSQL
      Breeder.all.where(['name ILIKE ?', "%#{ search_name }%"])
    else
      Breeder.all
    end
  end

  def self.fetch(name)
    unless name.empty? || name == nil || name == "---"
      breeder = Breeder.find_by name: name
      unless breeder
        breeder = Breeder.new name: name
        breeder.save!
      end
    end
    return breeder
  end

end

app/controllers/breeders_controller.rb
class BreedersController < ApplicationController
  before_action :set_breeder, only: [:show, :edit, :update, :destroy]

  # GET /breeders
  # GET /breeders.json
  def index
    ### TODO: How do I incorporate search_address when that is the button clicked?  Maybe some
    ###         Ajaxify magic?
    @breeders = Breeder.search_name(params[:search_name])
    if @breeders.class == Array
      @breeders = Kaminari.paginate_array(@breeders).page(params[:page])
    else
      @breeders = @breeders.page(params[:page]) # if @breeders is AR::Relation object
    end
  end

  # GET /breeders/1
  # GET /breeders/1.json
  def show
  end

  # GET /breeders/new
  def new
    @breeder = Breeder.new
  end

  # GET /breeders/1/edit
  def edit
  end

  # POST /breeders
  # POST /breeders.json
  def create
    @breeder = Breeder.new(breeder_params)
    authorize @breeder

    respond_to do |format|
      if @breeder.save
        format.html { redirect_to @breeder, notice: 'Breeder was successfully created.' }
        format.json { render action: 'show', status: :created, location: @breeder }
      else
        format.html { render action: 'new' }
        format.json { render json: @breeder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeders/1
  # PATCH/PUT /breeders/1.json
  def update
    respond_to do |format|
      if @breeder.update(breeder_params)
        format.html { redirect_to @breeder, notice: 'Breeder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @breeder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeders/1
  # DELETE /breeders/1.json
  def destroy
    authorize @breeder
    @breeder.destroy
    respond_to do |format|
      format.html { redirect_to breeders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breeder
      @breeder = Breeder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breeder_params
      params.require(:breeder).permit(:name, :address)
    end
end

app/views/breeders/_form.html.erb
<%= form_for(@breeder) do |f| %>
  <% if @breeder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breeder.errors.count, "error") %> prohibited this breeder from being saved:</h2>

      <ul>
      <% @breeder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
<% end %>

app/views/breeders/edit.html.erb
<title><%= @breeder.name %></title>

<h1>Editing breeder</h1>

<%= render 'form' %>

<div>
  <div class="breeder_edit_delete_breeder">
    <% if policy(Breeder).destroy? %>
      <%= link_to 'Delete Breeder', @breeder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </div>
</div>

<%= link_to 'Show', @breeder %> |
<%= link_to 'Back', breeders_path %>

app/views/breeders/index.html.erb
<title>Trakehner Breeders</title>

<div>
  <div id="breeder_index_header">
    <%= render 'shared/website_title' %><br>
    <h2><%= t 'breeders_index.trakehner_breeder' %></h2>
  </div>
</div>

<div>
  <div id="breeder_index_search">
    <br><br>
    <%= render 'layouts/breeder_search' %>
    <br><br>
  </div>
</div>

<style>th{background-color:black; color:white}</style>
<table border="1">
  <thead>
    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">Address</th>
    </tr>
  </thead>

  <tbody>
    <% @breeders.each do |breeder| %>
      <tr id="<%= breeder.id %>">
        <td><%= link_to breeder.name, breeder %></td>
        <td><%= breeder.address %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <div class="breeder_index_new_breeder">
    <% if policy(Breeder).create? %>
      <%= link_to 'New Breeder', new_breeder_path %>
    <% end %>
  </div>
  <div class="breeder_index_footer">
    <%= paginate @breeders %>
    <br><br>
    <%= link_to 'Home', root_path %>
  </div>
</div>

app/views/breeders/new.html.erb
<h1>New breeder</h1>

<%= render 'form' %>

<%= link_to 'Back', breeders_path %>

app/views/breeders/show.html.erb
<title><%= @breeder.name %></title>

<div id="show_breeder_header">
  <h2><%= t 'breeders_index.trakehner_breeder' %></h2></p><br>
</div>

<p id="notice"><%= notice %></p>

<style>
  td.thick {font-weight:bold;}
</style>

<table cellpadding="2" width="100%">
  <tbody>
    <tr>
      <td class="thick"><%= @breeder.name %></td>
    </tr>
    <tr>
      <td class="thick"><%= @breeder.address %></td>
    </tr>
  </tbody>
</table>

<br />
<br />

<% if @breeder.horses.any? %>
  <%= render 'horses/horses_index_table', {:horses => @breeder.horses} %>
<% end %>

<br />
<br />

<% if policy(Breeder).update? %>
  <%= link_to 'Edit', edit_breeder_path(@breeder), id: "edit_breeder_link" %> |
<% end %>
<%= link_to 'Back', breeders_path %>