config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|de/ do

    get '/contact' => 'static#contact'
    get '/about' => 'static#about'

    resources :breeders

    resources :horses do
      member do
        get 'progeny'
      end
    end

    devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end

    devise_scope :user do
      get "signout", :to => "devise/sessions#destroy"
    end

    root :to => 'home#index'
    get '/:locale' => 'home#index'

  end

end

app/views/layouts/_breeder_search.html.erb
<%= form_tag breeders_path, method: :get do %>
  <p>
    <%= text_field_tag :search_name, params[:search_name] %>
    <%= submit_tag "Search Breeder By Name", :name => nil %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='center responsive_text'>
  <p class='copyright_notice'><%= t 'shared.copyright' %> &copy; 2013-2016 Susan Prestage <%= t 'shared.and' %> Nathaniel Barnes</p>
</footer>

app/views/layouts/_header.html.erb
<div class="section-colored text-center">
  <div class="container">
    <div class="row">
      <div class"col-lg-12">
        <div id="user_header">
          <div class="nav">
            <% flash.each do |name, msg| %>
              <%= content_tag :div, msg, id: "flash_#{name}" %>
            <% end %>
          </div>
        </div>
      </div><!-- /.col -->
    </div><!-- /.row  -->
  </div><!-- /.container -->
</div>

app/views/layouts/_horse_search.html.erb
<div id="horse_search_bar">
  <%= form_tag horses_path, method: :get do %>

    <span class="horse_search_field">
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag t("sidebar.search"), :name => nil %>
    </span>

    <span class="has_image_checkbox">
      <%= check_box_tag :has_image, params[:has_image] %>
      <%= label_tag :has_image, t(" ") %>
      <span class='has_image_checkbox_label'>Has Image</span>
    </span>

  <% end %>
</div>

app/views/layouts/_index_table.html.erb
<div>

  <table class="horse_index">
    <thead>
      <tr>
        <th class="text-center"></th>
        <th class="text-center"><%= t 'horses_index.trakehner_name' %></th>
        <th><%= t 'horses_index.sex' %></th>
        <th>YOB</th>
        <th class="text-center"><%= t 'horses_index.sire' %></th>
        <th class="text-center"><%= t 'horses_index.dam' %></th>
        <th><%= t 'horses_index.color' %></th>
        <!-- TODO: When we finally get Height implemented, put it here -->
      </tr>
    </thead>

    <tbody>
      <% horses.each do |horse| %>
        <tr id="<%= horse.id %>">
          <% if horse.image_url %>
            <td><%= image_tag horse.image_url(:thumbnail).to_s %></td>
          <% else %>
            <td></td>
          <% end %>
          <td><%= link_to horse.name, horse %></td>
          <td>
            <% if horse.sex == "S" %>
              <%= t "gender.stallion" %>
            <% elsif horse.sex == "M" %>
              <%= t "gender.mare" %>
            <% elsif horse.sex == "G" %>
              <%= t "gender.gelding" %>
            <% else %>
              <%= horse.sex %>
            <% end %>
          </td>
          <td><%= horse.birth_year %></td>
          <td><%= link_to horse.sire.name, horse.sire %></td>
          <td><%= link_to horse.dam.name, horse.dam %></td>
          <td><%= horse.color %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_language_selector.html.erb
<span class='language_selector'>
  <%= link_to_unless_current "English", locale: "en" %> |
  <%= link_to_unless_current "Deutsche", locale: "de" %>
</span>

app/views/layouts/_show_horse_header.html.erb
<title><%= @horse.name %></title>

<% dod = "" %>
<% mature_height = "" %>
<% mare_family = "" %>

<div class="section-colored text-center">
  <div class="trakehnerHorseName">
    <tr><td>
      <table width='100%'>
        <tr>
          <td width='35%' align="center">
            <%= render 'layouts/trakehner_logo' %>
          </td>
          <td vertical-align="top" width='30%' align="center">
            <br>
            <h3 id="name"><%= @horse.name.upcase %></h3>
            <b><p><%= @horse.registration_number %></p></b>
            <br>
          </td>
          <td width='35%' align="center">
            <%= render 'layouts/trakehner_logo' %>
          </td>
        </tr>
      </table>
    </td></tr>
  </div>

  <p id="notice"><%= notice %></p>

  <figure>
    <% if @horse.image_url %>
      <%= image_tag @horse.image_url(:pedigree).to_s, :class => "horse_image" %>
    <% else %>
      <%= render 'layouts/no_picture_for_horse_image' %>
    <% end %>
  </figure>
</div>

<style>
  td.thick {font-weight:bold;}
</style>

<div class="section-colored text-center">
  <div class="trakehnerHorseData">
    <table cellpadding="2" width="100%">
      <tbody>
        <tr>
          <td align='right' width='10%'><%= "Foaled:" %></td>
          <td class="thick" align='left'><%= @horse.birth_year %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td align='right' width='10%'><%= "Color:" %></td>
          <td class="thick" align='left'><%= @horse.color %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td valign='top' align='right' width='10%'><%= "Gender:" %></td>
          <td valign='top' class="thick" align='left'><%= @horse.sex %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td valign='top' align='right' width='10%'><%= "Height:" %></td>
          <td class="thick" align='left'>
            <% if mature_height != "" %>
              <%= mature_height %>
              <%= " h" %>
            <% end %>
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td valign='top' align='right' width='10%'><%= "Mare family:" %></td>
          <td class="thick" align='left'><%= mare_family %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td valign='top' align='right' width='10%'><%= "Breeder:" %></td>
          <td class="thick" align='left'>
            <% if @horse.breeder %>
              <%= link_to "#{ @horse.breeder.name }", @horse.breeder %>
            <% end %>
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td class="thick" align='left'>
            <% if @horse.breeder %>
              <%= @horse.breeder.address %>
            <% end %>
          </td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<!-- TODO: make this a link to the performance link -->
<% if @horse.performance_records_available == "yes" %>
  <%= t "horses_index.performance_records_available" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'layouts/horse_search' %>
    <%= render 'layouts/language_selector' %>
    <div class='clear_div'></div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>

</html>